### ISSUE TITLE
Consider adding a special table for current state of order book

### ISSUE THREAD

**Issue by cjcobb23** [cjcobb23/clio#38]
`book_offers` is a little slow. Fetching 200 offers from a book can take 2 seconds. I'm not sure how fast this needs to be, but we should consider adding an extra table in the database for the current state of each order book. We could delete from this table as part of ETL.

**Comment by natenichols** [comment]
This is tricky in cassanda, where deletes leave tombstones for (by default) ten days. A tombstone is just an entry w/ all null values.

This makes reads much less performant

**Comment by cjcobb23** [comment]
How slow is it? I would think that it would still be a lot faster than the current query for `book_offers`

**Comment by natenichols** [comment]
I haven't tested it w/ a 10 day (250,000) ledger load, but also keep in mind that because of the way we do `insert w/ TTL`, the inital load will bloat the database

**Comment by cjcobb23** [comment]
Ended up not being worth it. We are now just caching the validated ledger.
